//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/[Dev4]FlightSim/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/[Dev4]FlightSim/InputMap.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputMap: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""FlightControls"",
            ""id"": ""1b45f00a-3ed4-4d76-865a-c6eda1f0a5a2"",
            ""actions"": [
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Button"",
                    ""id"": ""15f3a9c0-f2f7-4ca6-8905-c70bea263c71"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ImpulseThrust"",
                    ""type"": ""Button"",
                    ""id"": ""b07dc9a3-a571-4354-8200-1a8a3abf468b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AirBrakes"",
                    ""type"": ""Button"",
                    ""id"": ""5e48aa2d-fa26-49d9-8312-62403302a761"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hovering"",
                    ""type"": ""Button"",
                    ""id"": ""794bab40-801c-4917-b5dc-5b7340943e0a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleSASMode"",
                    ""type"": ""Button"",
                    ""id"": ""466d0984-732d-4329-b907-578e46475969"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleHoverMode"",
                    ""type"": ""Button"",
                    ""id"": ""5e49db7a-66e9-4446-bd98-c059880cc06f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""54bbe36d-2fb5-4cb7-b08e-401b31a88706"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Orientation"",
                    ""type"": ""Value"",
                    ""id"": ""a548b4f8-7a8b-4724-a135-c3199c1b8d79"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Thrust Controls"",
                    ""id"": ""a7c92610-83ac-4fca-9ace-6f3b1b9b00e8"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""882074c5-3e45-4d26-bb94-5e5c9aa8f5e1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""46b54ed7-a7a9-44c3-bfd9-d2ce934c671b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""265d7793-517b-4820-9702-7c4a7f0fa99f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8f13d1b6-b891-4921-af65-cd5abb633f7d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""485941ae-7363-4dd5-920d-8fd74bf7c3c2"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e654c6af-9686-466a-ad44-c16f567844fb"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""AirBrakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""b7e46e53-422a-4df1-bb69-c631d08b0d30"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AirBrakes"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""15034e63-31ac-456a-891e-0fbbf0c85506"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""AirBrakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d0e18bd5-946d-46b3-a90e-2fa34bb3f5b1"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""AirBrakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f26ef8fb-fc20-4162-a934-a2d230992622"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ImpulseThrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""afcbad03-a97e-4685-8065-c0fca06aa0c5"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ImpulseThrust"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d332c4b3-de99-4706-8155-6f4e7ac8de01"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ImpulseThrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""04265d83-8ef6-4e21-866d-33fe00db673b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ImpulseThrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8f35f32d-76f3-4173-bb70-2ab88f534656"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Hovering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""047202a5-b4d1-4ae6-927c-0b7ab3fbc45f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Hovering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a342e0b4-d4d5-49ea-aeb2-9b4e1b97def3"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ScrollAxis"",
                    ""id"": ""88616ab2-a41e-489b-a040-5247fa2da8b1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleHoverMode"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""39340c75-7a98-49d6-b7ad-0eddd72352ca"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ToggleHoverMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0fc4570d-58c1-4316-9393-7f885f2b5518"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ToggleHoverMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""76c88a25-c91f-47a6-a365-a0e3db988317"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleHoverMode"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c0609f75-ed23-4354-85e7-c483ce43d297"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ToggleHoverMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0300c286-ca28-42e6-b52b-354681309693"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ToggleHoverMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ff289981-0d4c-4d70-8f49-f88a0a12a913"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""ToggleSASMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ec8baab-105b-4369-bf69-5f5dba188a59"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ToggleSASMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""3D Vector - PC"",
                    ""id"": ""ac0236d3-d03c-4239-b790-e3e5f11aaf44"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Orientation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2a7bbc2a-33f2-495a-b72a-6d16c3a41d67"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f1db07bd-d9f2-4d41-96e5-644753760fa9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e83d0c62-4321-4d48-aec8-2a734b9aaf7c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2229e02b-91ce-41aa-a7c9-36cfb619b9fd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""0ac4453e-9777-4352-9efa-bf869ed41f7f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""2e132516-c5e9-4e50-a895-4e31dcc7f71a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""3D Vector - Controller"",
                    ""id"": ""39c52618-ef96-482d-ac43-fd4bd39a5ede"",
                    ""path"": ""3DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Orientation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""05bc53ce-9caa-4d80-9dc3-11c96d7b214e"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0391a216-ba7a-40fb-a2f8-9144ee7cbed0"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f7b942d3-aa94-4da1-a7f2-d693a7a52e46"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""afe65022-e51a-43e8-bbca-aeaf78652462"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""3c6fd956-07b7-4c37-ad16-0e1cb08b8d44"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""8e7d8f35-567d-4927-9f32-cf79f8579cd6"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""UIControls"",
            ""id"": ""e4758a46-db03-4044-8776-2972b5e0b140"",
            ""actions"": [
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""002d82b7-a537-4b29-a902-b0242c2247e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveCam"",
                    ""type"": ""Value"",
                    ""id"": ""89ec40ff-849b-4b33-bfef-43a4592e28c0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CamZoomMod"",
                    ""type"": ""Button"",
                    ""id"": ""5c1a6b8d-a387-4cc8-a775-037b62f82f8b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CamPivotMod"",
                    ""type"": ""Button"",
                    ""id"": ""bc9765a0-d90a-4f37-af01-626b716e1c2f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CamResetPivot"",
                    ""type"": ""Button"",
                    ""id"": ""f6d4ab7e-276e-456a-ba4c-725397409cdf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7372beb3-0c12-4470-a1d7-848f0208d680"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da4a07ce-0739-4242-b99a-52a1d2152118"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""753477a3-232d-44de-8947-1802075b2fac"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCam"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ac82ee5f-48bf-4186-80eb-1ff6cd6a943d"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""MoveCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3082a394-d138-41aa-ab9b-9b29002b90dd"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""MoveCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f55f403f-cfff-4523-89c0-ca50a41b8956"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""MoveCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d551da37-2a91-4f17-89c7-2dd9360d374c"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""MoveCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""3c2eb37e-fb70-4967-9285-2026d0bf3632"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamZoomMod"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""115d832e-ffd1-453e-bb7b-6fbad16391b9"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""CamZoomMod"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""9f585797-e0fa-4d18-b962-27ac3df219d3"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""CamZoomMod"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d1df1249-cd72-4432-8a19-8e4fc1e28012"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""CamResetPivot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18985ea9-ea51-4edf-bb3f-5cc7dfeb126a"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""CamPivotMod"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dev"",
            ""id"": ""8648cdd1-ffcd-4ef2-8c64-d423a395a3ab"",
            ""actions"": [
                {
                    ""name"": ""ResetDrone"",
                    ""type"": ""Button"",
                    ""id"": ""771b7114-93e2-4115-9cb6-2a7ef4bcc4b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDevTools"",
                    ""type"": ""Button"",
                    ""id"": ""a10880dd-d888-4ce5-b886-7bd9449f1321"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AssignGameState"",
                    ""type"": ""Value"",
                    ""id"": ""50242938-59a5-45b4-b5f3-176c8359ec2a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6d7e5422-9da9-4459-bbfb-09e58bcfac3e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0d9b298a-cc9a-4d60-9154-f683a1ebcf8c"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""819abb0c-27da-485a-ade1-d36f411af54a"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""2e9bb012-b81a-4a10-90d6-9a133d5d3670"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""b767fd88-282d-41a3-a15d-db831a250cf6"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""35676b5e-a2cf-442a-87bd-d5ec3a1ea36d"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""42b5473d-bc1e-4196-80f9-c14ce199eb52"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""ToggleDevTools"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae608cc9-f578-4d14-bfe8-7c1f08db7a16"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.1)"",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""AssignGameState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb116606-0954-48d8-b0b9-20aa3c4d7501"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.2)"",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""AssignGameState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f0d26ef-cd2c-4c71-8196-ce5e1e7114b4"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.3)"",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""AssignGameState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bd50f39-614d-438a-9b31-7496aeb46110"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.4)"",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""AssignGameState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e12699b-9785-4811-bb05-4094474023d5"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.5)"",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""AssignGameState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b234a3a-3d24-455e-90e0-01de308a5443"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.6)"",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""AssignGameState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d43725a-7273-442a-86c9-acf09872d56b"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.8)"",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""AssignGameState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f0d2c0b-2536-4342-8c1c-c731a006b716"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=-1)"",
                    ""groups"": "";PC - KeyMouse (Standard)"",
                    ""action"": ""AssignGameState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC - KeyMouse (Standard)"",
            ""bindingGroup"": ""PC - KeyMouse (Standard)"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // FlightControls
        m_FlightControls = asset.FindActionMap("FlightControls", throwIfNotFound: true);
        m_FlightControls_Thrust = m_FlightControls.FindAction("Thrust", throwIfNotFound: true);
        m_FlightControls_ImpulseThrust = m_FlightControls.FindAction("ImpulseThrust", throwIfNotFound: true);
        m_FlightControls_AirBrakes = m_FlightControls.FindAction("AirBrakes", throwIfNotFound: true);
        m_FlightControls_Hovering = m_FlightControls.FindAction("Hovering", throwIfNotFound: true);
        m_FlightControls_ToggleSASMode = m_FlightControls.FindAction("ToggleSASMode", throwIfNotFound: true);
        m_FlightControls_ToggleHoverMode = m_FlightControls.FindAction("ToggleHoverMode", throwIfNotFound: true);
        m_FlightControls_MouseClick = m_FlightControls.FindAction("MouseClick", throwIfNotFound: true);
        m_FlightControls_Orientation = m_FlightControls.FindAction("Orientation", throwIfNotFound: true);
        // UIControls
        m_UIControls = asset.FindActionMap("UIControls", throwIfNotFound: true);
        m_UIControls_Esc = m_UIControls.FindAction("Esc", throwIfNotFound: true);
        m_UIControls_MoveCam = m_UIControls.FindAction("MoveCam", throwIfNotFound: true);
        m_UIControls_CamZoomMod = m_UIControls.FindAction("CamZoomMod", throwIfNotFound: true);
        m_UIControls_CamPivotMod = m_UIControls.FindAction("CamPivotMod", throwIfNotFound: true);
        m_UIControls_CamResetPivot = m_UIControls.FindAction("CamResetPivot", throwIfNotFound: true);
        // Dev
        m_Dev = asset.FindActionMap("Dev", throwIfNotFound: true);
        m_Dev_ResetDrone = m_Dev.FindAction("ResetDrone", throwIfNotFound: true);
        m_Dev_ToggleDevTools = m_Dev.FindAction("ToggleDevTools", throwIfNotFound: true);
        m_Dev_AssignGameState = m_Dev.FindAction("AssignGameState", throwIfNotFound: true);
    }

    ~@InputMap()
    {
        UnityEngine.Debug.Assert(!m_FlightControls.enabled, "This will cause a leak and performance issues, InputMap.FlightControls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UIControls.enabled, "This will cause a leak and performance issues, InputMap.UIControls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Dev.enabled, "This will cause a leak and performance issues, InputMap.Dev.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FlightControls
    private readonly InputActionMap m_FlightControls;
    private List<IFlightControlsActions> m_FlightControlsActionsCallbackInterfaces = new List<IFlightControlsActions>();
    private readonly InputAction m_FlightControls_Thrust;
    private readonly InputAction m_FlightControls_ImpulseThrust;
    private readonly InputAction m_FlightControls_AirBrakes;
    private readonly InputAction m_FlightControls_Hovering;
    private readonly InputAction m_FlightControls_ToggleSASMode;
    private readonly InputAction m_FlightControls_ToggleHoverMode;
    private readonly InputAction m_FlightControls_MouseClick;
    private readonly InputAction m_FlightControls_Orientation;
    /// <summary>
    /// Provides access to input actions defined in input action map "FlightControls".
    /// </summary>
    public struct FlightControlsActions
    {
        private @InputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public FlightControlsActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/Thrust".
        /// </summary>
        public InputAction @Thrust => m_Wrapper.m_FlightControls_Thrust;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/ImpulseThrust".
        /// </summary>
        public InputAction @ImpulseThrust => m_Wrapper.m_FlightControls_ImpulseThrust;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/AirBrakes".
        /// </summary>
        public InputAction @AirBrakes => m_Wrapper.m_FlightControls_AirBrakes;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/Hovering".
        /// </summary>
        public InputAction @Hovering => m_Wrapper.m_FlightControls_Hovering;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/ToggleSASMode".
        /// </summary>
        public InputAction @ToggleSASMode => m_Wrapper.m_FlightControls_ToggleSASMode;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/ToggleHoverMode".
        /// </summary>
        public InputAction @ToggleHoverMode => m_Wrapper.m_FlightControls_ToggleHoverMode;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/MouseClick".
        /// </summary>
        public InputAction @MouseClick => m_Wrapper.m_FlightControls_MouseClick;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/Orientation".
        /// </summary>
        public InputAction @Orientation => m_Wrapper.m_FlightControls_Orientation;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_FlightControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="FlightControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(FlightControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="FlightControlsActions" />
        public void AddCallbacks(IFlightControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_FlightControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlightControlsActionsCallbackInterfaces.Add(instance);
            @Thrust.started += instance.OnThrust;
            @Thrust.performed += instance.OnThrust;
            @Thrust.canceled += instance.OnThrust;
            @ImpulseThrust.started += instance.OnImpulseThrust;
            @ImpulseThrust.performed += instance.OnImpulseThrust;
            @ImpulseThrust.canceled += instance.OnImpulseThrust;
            @AirBrakes.started += instance.OnAirBrakes;
            @AirBrakes.performed += instance.OnAirBrakes;
            @AirBrakes.canceled += instance.OnAirBrakes;
            @Hovering.started += instance.OnHovering;
            @Hovering.performed += instance.OnHovering;
            @Hovering.canceled += instance.OnHovering;
            @ToggleSASMode.started += instance.OnToggleSASMode;
            @ToggleSASMode.performed += instance.OnToggleSASMode;
            @ToggleSASMode.canceled += instance.OnToggleSASMode;
            @ToggleHoverMode.started += instance.OnToggleHoverMode;
            @ToggleHoverMode.performed += instance.OnToggleHoverMode;
            @ToggleHoverMode.canceled += instance.OnToggleHoverMode;
            @MouseClick.started += instance.OnMouseClick;
            @MouseClick.performed += instance.OnMouseClick;
            @MouseClick.canceled += instance.OnMouseClick;
            @Orientation.started += instance.OnOrientation;
            @Orientation.performed += instance.OnOrientation;
            @Orientation.canceled += instance.OnOrientation;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="FlightControlsActions" />
        private void UnregisterCallbacks(IFlightControlsActions instance)
        {
            @Thrust.started -= instance.OnThrust;
            @Thrust.performed -= instance.OnThrust;
            @Thrust.canceled -= instance.OnThrust;
            @ImpulseThrust.started -= instance.OnImpulseThrust;
            @ImpulseThrust.performed -= instance.OnImpulseThrust;
            @ImpulseThrust.canceled -= instance.OnImpulseThrust;
            @AirBrakes.started -= instance.OnAirBrakes;
            @AirBrakes.performed -= instance.OnAirBrakes;
            @AirBrakes.canceled -= instance.OnAirBrakes;
            @Hovering.started -= instance.OnHovering;
            @Hovering.performed -= instance.OnHovering;
            @Hovering.canceled -= instance.OnHovering;
            @ToggleSASMode.started -= instance.OnToggleSASMode;
            @ToggleSASMode.performed -= instance.OnToggleSASMode;
            @ToggleSASMode.canceled -= instance.OnToggleSASMode;
            @ToggleHoverMode.started -= instance.OnToggleHoverMode;
            @ToggleHoverMode.performed -= instance.OnToggleHoverMode;
            @ToggleHoverMode.canceled -= instance.OnToggleHoverMode;
            @MouseClick.started -= instance.OnMouseClick;
            @MouseClick.performed -= instance.OnMouseClick;
            @MouseClick.canceled -= instance.OnMouseClick;
            @Orientation.started -= instance.OnOrientation;
            @Orientation.performed -= instance.OnOrientation;
            @Orientation.canceled -= instance.OnOrientation;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FlightControlsActions.UnregisterCallbacks(IFlightControlsActions)" />.
        /// </summary>
        /// <seealso cref="FlightControlsActions.UnregisterCallbacks(IFlightControlsActions)" />
        public void RemoveCallbacks(IFlightControlsActions instance)
        {
            if (m_Wrapper.m_FlightControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="FlightControlsActions.AddCallbacks(IFlightControlsActions)" />
        /// <seealso cref="FlightControlsActions.RemoveCallbacks(IFlightControlsActions)" />
        /// <seealso cref="FlightControlsActions.UnregisterCallbacks(IFlightControlsActions)" />
        public void SetCallbacks(IFlightControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_FlightControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlightControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="FlightControlsActions" /> instance referencing this action map.
    /// </summary>
    public FlightControlsActions @FlightControls => new FlightControlsActions(this);

    // UIControls
    private readonly InputActionMap m_UIControls;
    private List<IUIControlsActions> m_UIControlsActionsCallbackInterfaces = new List<IUIControlsActions>();
    private readonly InputAction m_UIControls_Esc;
    private readonly InputAction m_UIControls_MoveCam;
    private readonly InputAction m_UIControls_CamZoomMod;
    private readonly InputAction m_UIControls_CamPivotMod;
    private readonly InputAction m_UIControls_CamResetPivot;
    /// <summary>
    /// Provides access to input actions defined in input action map "UIControls".
    /// </summary>
    public struct UIControlsActions
    {
        private @InputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UIControlsActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UIControls/Esc".
        /// </summary>
        public InputAction @Esc => m_Wrapper.m_UIControls_Esc;
        /// <summary>
        /// Provides access to the underlying input action "UIControls/MoveCam".
        /// </summary>
        public InputAction @MoveCam => m_Wrapper.m_UIControls_MoveCam;
        /// <summary>
        /// Provides access to the underlying input action "UIControls/CamZoomMod".
        /// </summary>
        public InputAction @CamZoomMod => m_Wrapper.m_UIControls_CamZoomMod;
        /// <summary>
        /// Provides access to the underlying input action "UIControls/CamPivotMod".
        /// </summary>
        public InputAction @CamPivotMod => m_Wrapper.m_UIControls_CamPivotMod;
        /// <summary>
        /// Provides access to the underlying input action "UIControls/CamResetPivot".
        /// </summary>
        public InputAction @CamResetPivot => m_Wrapper.m_UIControls_CamResetPivot;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UIControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UIControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UIControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UIControlsActions" />
        public void AddCallbacks(IUIControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_UIControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIControlsActionsCallbackInterfaces.Add(instance);
            @Esc.started += instance.OnEsc;
            @Esc.performed += instance.OnEsc;
            @Esc.canceled += instance.OnEsc;
            @MoveCam.started += instance.OnMoveCam;
            @MoveCam.performed += instance.OnMoveCam;
            @MoveCam.canceled += instance.OnMoveCam;
            @CamZoomMod.started += instance.OnCamZoomMod;
            @CamZoomMod.performed += instance.OnCamZoomMod;
            @CamZoomMod.canceled += instance.OnCamZoomMod;
            @CamPivotMod.started += instance.OnCamPivotMod;
            @CamPivotMod.performed += instance.OnCamPivotMod;
            @CamPivotMod.canceled += instance.OnCamPivotMod;
            @CamResetPivot.started += instance.OnCamResetPivot;
            @CamResetPivot.performed += instance.OnCamResetPivot;
            @CamResetPivot.canceled += instance.OnCamResetPivot;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UIControlsActions" />
        private void UnregisterCallbacks(IUIControlsActions instance)
        {
            @Esc.started -= instance.OnEsc;
            @Esc.performed -= instance.OnEsc;
            @Esc.canceled -= instance.OnEsc;
            @MoveCam.started -= instance.OnMoveCam;
            @MoveCam.performed -= instance.OnMoveCam;
            @MoveCam.canceled -= instance.OnMoveCam;
            @CamZoomMod.started -= instance.OnCamZoomMod;
            @CamZoomMod.performed -= instance.OnCamZoomMod;
            @CamZoomMod.canceled -= instance.OnCamZoomMod;
            @CamPivotMod.started -= instance.OnCamPivotMod;
            @CamPivotMod.performed -= instance.OnCamPivotMod;
            @CamPivotMod.canceled -= instance.OnCamPivotMod;
            @CamResetPivot.started -= instance.OnCamResetPivot;
            @CamResetPivot.performed -= instance.OnCamResetPivot;
            @CamResetPivot.canceled -= instance.OnCamResetPivot;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UIControlsActions.UnregisterCallbacks(IUIControlsActions)" />.
        /// </summary>
        /// <seealso cref="UIControlsActions.UnregisterCallbacks(IUIControlsActions)" />
        public void RemoveCallbacks(IUIControlsActions instance)
        {
            if (m_Wrapper.m_UIControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UIControlsActions.AddCallbacks(IUIControlsActions)" />
        /// <seealso cref="UIControlsActions.RemoveCallbacks(IUIControlsActions)" />
        /// <seealso cref="UIControlsActions.UnregisterCallbacks(IUIControlsActions)" />
        public void SetCallbacks(IUIControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_UIControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UIControlsActions" /> instance referencing this action map.
    /// </summary>
    public UIControlsActions @UIControls => new UIControlsActions(this);

    // Dev
    private readonly InputActionMap m_Dev;
    private List<IDevActions> m_DevActionsCallbackInterfaces = new List<IDevActions>();
    private readonly InputAction m_Dev_ResetDrone;
    private readonly InputAction m_Dev_ToggleDevTools;
    private readonly InputAction m_Dev_AssignGameState;
    /// <summary>
    /// Provides access to input actions defined in input action map "Dev".
    /// </summary>
    public struct DevActions
    {
        private @InputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public DevActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Dev/ResetDrone".
        /// </summary>
        public InputAction @ResetDrone => m_Wrapper.m_Dev_ResetDrone;
        /// <summary>
        /// Provides access to the underlying input action "Dev/ToggleDevTools".
        /// </summary>
        public InputAction @ToggleDevTools => m_Wrapper.m_Dev_ToggleDevTools;
        /// <summary>
        /// Provides access to the underlying input action "Dev/AssignGameState".
        /// </summary>
        public InputAction @AssignGameState => m_Wrapper.m_Dev_AssignGameState;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Dev; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="DevActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(DevActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="DevActions" />
        public void AddCallbacks(IDevActions instance)
        {
            if (instance == null || m_Wrapper.m_DevActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DevActionsCallbackInterfaces.Add(instance);
            @ResetDrone.started += instance.OnResetDrone;
            @ResetDrone.performed += instance.OnResetDrone;
            @ResetDrone.canceled += instance.OnResetDrone;
            @ToggleDevTools.started += instance.OnToggleDevTools;
            @ToggleDevTools.performed += instance.OnToggleDevTools;
            @ToggleDevTools.canceled += instance.OnToggleDevTools;
            @AssignGameState.started += instance.OnAssignGameState;
            @AssignGameState.performed += instance.OnAssignGameState;
            @AssignGameState.canceled += instance.OnAssignGameState;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="DevActions" />
        private void UnregisterCallbacks(IDevActions instance)
        {
            @ResetDrone.started -= instance.OnResetDrone;
            @ResetDrone.performed -= instance.OnResetDrone;
            @ResetDrone.canceled -= instance.OnResetDrone;
            @ToggleDevTools.started -= instance.OnToggleDevTools;
            @ToggleDevTools.performed -= instance.OnToggleDevTools;
            @ToggleDevTools.canceled -= instance.OnToggleDevTools;
            @AssignGameState.started -= instance.OnAssignGameState;
            @AssignGameState.performed -= instance.OnAssignGameState;
            @AssignGameState.canceled -= instance.OnAssignGameState;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DevActions.UnregisterCallbacks(IDevActions)" />.
        /// </summary>
        /// <seealso cref="DevActions.UnregisterCallbacks(IDevActions)" />
        public void RemoveCallbacks(IDevActions instance)
        {
            if (m_Wrapper.m_DevActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="DevActions.AddCallbacks(IDevActions)" />
        /// <seealso cref="DevActions.RemoveCallbacks(IDevActions)" />
        /// <seealso cref="DevActions.UnregisterCallbacks(IDevActions)" />
        public void SetCallbacks(IDevActions instance)
        {
            foreach (var item in m_Wrapper.m_DevActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DevActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="DevActions" /> instance referencing this action map.
    /// </summary>
    public DevActions @Dev => new DevActions(this);
    private int m_PCKeyMouseStandardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme PCKeyMouseStandardScheme
    {
        get
        {
            if (m_PCKeyMouseStandardSchemeIndex == -1) m_PCKeyMouseStandardSchemeIndex = asset.FindControlSchemeIndex("PC - KeyMouse (Standard)");
            return asset.controlSchemes[m_PCKeyMouseStandardSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "FlightControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="FlightControlsActions.AddCallbacks(IFlightControlsActions)" />
    /// <seealso cref="FlightControlsActions.RemoveCallbacks(IFlightControlsActions)" />
    public interface IFlightControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Thrust" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrust(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ImpulseThrust" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnImpulseThrust(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AirBrakes" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAirBrakes(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Hovering" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHovering(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleSASMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleSASMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleHoverMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleHoverMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MouseClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Orientation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOrientation(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UIControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UIControlsActions.AddCallbacks(IUIControlsActions)" />
    /// <seealso cref="UIControlsActions.RemoveCallbacks(IUIControlsActions)" />
    public interface IUIControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Esc" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEsc(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveCam" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveCam(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CamZoomMod" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamZoomMod(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CamPivotMod" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamPivotMod(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CamResetPivot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamResetPivot(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Dev" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="DevActions.AddCallbacks(IDevActions)" />
    /// <seealso cref="DevActions.RemoveCallbacks(IDevActions)" />
    public interface IDevActions
    {
        /// <summary>
        /// Method invoked when associated input action "ResetDrone" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnResetDrone(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ToggleDevTools" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleDevTools(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AssignGameState" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAssignGameState(InputAction.CallbackContext context);
    }
}
