//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/[Dev4]FlightSim/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/[Dev4]FlightSim/InputMap.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputMap: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""FlightControls"",
            ""id"": ""1b45f00a-3ed4-4d76-865a-c6eda1f0a5a2"",
            ""actions"": [
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Button"",
                    ""id"": ""15f3a9c0-f2f7-4ca6-8905-c70bea263c71"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ImpulseThrust"",
                    ""type"": ""Button"",
                    ""id"": ""b07dc9a3-a571-4354-8200-1a8a3abf468b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AirBrakes"",
                    ""type"": ""Button"",
                    ""id"": ""5e48aa2d-fa26-49d9-8312-62403302a761"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hovering"",
                    ""type"": ""Button"",
                    ""id"": ""794bab40-801c-4917-b5dc-5b7340943e0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseScroll"",
                    ""type"": ""Button"",
                    ""id"": ""5e49db7a-66e9-4446-bd98-c059880cc06f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""54bbe36d-2fb5-4cb7-b08e-401b31a88706"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Thrust Controls"",
                    ""id"": ""a7c92610-83ac-4fca-9ace-6f3b1b9b00e8"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""882074c5-3e45-4d26-bb94-5e5c9aa8f5e1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""46b54ed7-a7a9-44c3-bfd9-d2ce934c671b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e654c6af-9686-466a-ad44-c16f567844fb"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""AirBrakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f26ef8fb-fc20-4162-a934-a2d230992622"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ImpulseThrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f35f32d-76f3-4173-bb70-2ab88f534656"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Hovering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a342e0b4-d4d5-49ea-aeb2-9b4e1b97def3"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ScrollAxis"",
                    ""id"": ""88616ab2-a41e-489b-a040-5247fa2da8b1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""39340c75-7a98-49d6-b7ad-0eddd72352ca"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0fc4570d-58c1-4316-9393-7f885f2b5518"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""ControlSurfaces"",
            ""id"": ""cf501cd6-3384-431b-ac67-68a563aa565e"",
            ""actions"": [
                {
                    ""name"": ""PitchUp"",
                    ""type"": ""Button"",
                    ""id"": ""9d9ddf46-e7e0-487c-90f9-59a8a915a2c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PitchDown"",
                    ""type"": ""Button"",
                    ""id"": ""0e742c79-d6ca-424f-b0de-ec8a55837695"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollClock"",
                    ""type"": ""Button"",
                    ""id"": ""0a806f74-d753-4dd1-b478-4e2298d72955"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollCounterClock"",
                    ""type"": ""Button"",
                    ""id"": ""9506b580-e4e3-44aa-bff1-291b29297354"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YawRight"",
                    ""type"": ""Button"",
                    ""id"": ""e28b97d5-8f97-43f6-bd2a-856a19de330e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YawLeft"",
                    ""type"": ""Button"",
                    ""id"": ""de49f581-4d65-40e8-9089-4f36be6c3ea6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3688190a-ebe9-4da5-9f92-5d6fdb4e8823"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""PitchUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c835dad-b094-4244-b9d1-bca5d2b7e8cc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""PitchDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56420366-f013-4678-8400-2e8b192c0f5f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""RollClock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c448fb7a-8169-4bbc-9321-21db88e9636f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""RollCounterClock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0544b26b-b39b-479b-86d7-f2ec9f5fe23b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""YawRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59321424-5785-42b0-8a50-e8b42652db78"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""YawLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dev"",
            ""id"": ""8648cdd1-ffcd-4ef2-8c64-d423a395a3ab"",
            ""actions"": [
                {
                    ""name"": ""ResetDrone"",
                    ""type"": ""Button"",
                    ""id"": ""771b7114-93e2-4115-9cb6-2a7ef4bcc4b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6d7e5422-9da9-4459-bbfb-09e58bcfac3e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0d9b298a-cc9a-4d60-9154-f683a1ebcf8c"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""819abb0c-27da-485a-ade1-d36f411af54a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ResetDrone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC - KeyMouse (Standard)"",
            ""bindingGroup"": ""PC - KeyMouse (Standard)"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // FlightControls
        m_FlightControls = asset.FindActionMap("FlightControls", throwIfNotFound: true);
        m_FlightControls_Thrust = m_FlightControls.FindAction("Thrust", throwIfNotFound: true);
        m_FlightControls_ImpulseThrust = m_FlightControls.FindAction("ImpulseThrust", throwIfNotFound: true);
        m_FlightControls_AirBrakes = m_FlightControls.FindAction("AirBrakes", throwIfNotFound: true);
        m_FlightControls_Hovering = m_FlightControls.FindAction("Hovering", throwIfNotFound: true);
        m_FlightControls_MouseScroll = m_FlightControls.FindAction("MouseScroll", throwIfNotFound: true);
        m_FlightControls_MouseClick = m_FlightControls.FindAction("MouseClick", throwIfNotFound: true);
        // ControlSurfaces
        m_ControlSurfaces = asset.FindActionMap("ControlSurfaces", throwIfNotFound: true);
        m_ControlSurfaces_PitchUp = m_ControlSurfaces.FindAction("PitchUp", throwIfNotFound: true);
        m_ControlSurfaces_PitchDown = m_ControlSurfaces.FindAction("PitchDown", throwIfNotFound: true);
        m_ControlSurfaces_RollClock = m_ControlSurfaces.FindAction("RollClock", throwIfNotFound: true);
        m_ControlSurfaces_RollCounterClock = m_ControlSurfaces.FindAction("RollCounterClock", throwIfNotFound: true);
        m_ControlSurfaces_YawRight = m_ControlSurfaces.FindAction("YawRight", throwIfNotFound: true);
        m_ControlSurfaces_YawLeft = m_ControlSurfaces.FindAction("YawLeft", throwIfNotFound: true);
        // Dev
        m_Dev = asset.FindActionMap("Dev", throwIfNotFound: true);
        m_Dev_ResetDrone = m_Dev.FindAction("ResetDrone", throwIfNotFound: true);
    }

    ~@InputMap()
    {
        UnityEngine.Debug.Assert(!m_FlightControls.enabled, "This will cause a leak and performance issues, InputMap.FlightControls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_ControlSurfaces.enabled, "This will cause a leak and performance issues, InputMap.ControlSurfaces.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Dev.enabled, "This will cause a leak and performance issues, InputMap.Dev.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FlightControls
    private readonly InputActionMap m_FlightControls;
    private List<IFlightControlsActions> m_FlightControlsActionsCallbackInterfaces = new List<IFlightControlsActions>();
    private readonly InputAction m_FlightControls_Thrust;
    private readonly InputAction m_FlightControls_ImpulseThrust;
    private readonly InputAction m_FlightControls_AirBrakes;
    private readonly InputAction m_FlightControls_Hovering;
    private readonly InputAction m_FlightControls_MouseScroll;
    private readonly InputAction m_FlightControls_MouseClick;
    /// <summary>
    /// Provides access to input actions defined in input action map "FlightControls".
    /// </summary>
    public struct FlightControlsActions
    {
        private @InputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public FlightControlsActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/Thrust".
        /// </summary>
        public InputAction @Thrust => m_Wrapper.m_FlightControls_Thrust;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/ImpulseThrust".
        /// </summary>
        public InputAction @ImpulseThrust => m_Wrapper.m_FlightControls_ImpulseThrust;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/AirBrakes".
        /// </summary>
        public InputAction @AirBrakes => m_Wrapper.m_FlightControls_AirBrakes;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/Hovering".
        /// </summary>
        public InputAction @Hovering => m_Wrapper.m_FlightControls_Hovering;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/MouseScroll".
        /// </summary>
        public InputAction @MouseScroll => m_Wrapper.m_FlightControls_MouseScroll;
        /// <summary>
        /// Provides access to the underlying input action "FlightControls/MouseClick".
        /// </summary>
        public InputAction @MouseClick => m_Wrapper.m_FlightControls_MouseClick;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_FlightControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="FlightControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(FlightControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="FlightControlsActions" />
        public void AddCallbacks(IFlightControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_FlightControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlightControlsActionsCallbackInterfaces.Add(instance);
            @Thrust.started += instance.OnThrust;
            @Thrust.performed += instance.OnThrust;
            @Thrust.canceled += instance.OnThrust;
            @ImpulseThrust.started += instance.OnImpulseThrust;
            @ImpulseThrust.performed += instance.OnImpulseThrust;
            @ImpulseThrust.canceled += instance.OnImpulseThrust;
            @AirBrakes.started += instance.OnAirBrakes;
            @AirBrakes.performed += instance.OnAirBrakes;
            @AirBrakes.canceled += instance.OnAirBrakes;
            @Hovering.started += instance.OnHovering;
            @Hovering.performed += instance.OnHovering;
            @Hovering.canceled += instance.OnHovering;
            @MouseScroll.started += instance.OnMouseScroll;
            @MouseScroll.performed += instance.OnMouseScroll;
            @MouseScroll.canceled += instance.OnMouseScroll;
            @MouseClick.started += instance.OnMouseClick;
            @MouseClick.performed += instance.OnMouseClick;
            @MouseClick.canceled += instance.OnMouseClick;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="FlightControlsActions" />
        private void UnregisterCallbacks(IFlightControlsActions instance)
        {
            @Thrust.started -= instance.OnThrust;
            @Thrust.performed -= instance.OnThrust;
            @Thrust.canceled -= instance.OnThrust;
            @ImpulseThrust.started -= instance.OnImpulseThrust;
            @ImpulseThrust.performed -= instance.OnImpulseThrust;
            @ImpulseThrust.canceled -= instance.OnImpulseThrust;
            @AirBrakes.started -= instance.OnAirBrakes;
            @AirBrakes.performed -= instance.OnAirBrakes;
            @AirBrakes.canceled -= instance.OnAirBrakes;
            @Hovering.started -= instance.OnHovering;
            @Hovering.performed -= instance.OnHovering;
            @Hovering.canceled -= instance.OnHovering;
            @MouseScroll.started -= instance.OnMouseScroll;
            @MouseScroll.performed -= instance.OnMouseScroll;
            @MouseScroll.canceled -= instance.OnMouseScroll;
            @MouseClick.started -= instance.OnMouseClick;
            @MouseClick.performed -= instance.OnMouseClick;
            @MouseClick.canceled -= instance.OnMouseClick;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FlightControlsActions.UnregisterCallbacks(IFlightControlsActions)" />.
        /// </summary>
        /// <seealso cref="FlightControlsActions.UnregisterCallbacks(IFlightControlsActions)" />
        public void RemoveCallbacks(IFlightControlsActions instance)
        {
            if (m_Wrapper.m_FlightControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="FlightControlsActions.AddCallbacks(IFlightControlsActions)" />
        /// <seealso cref="FlightControlsActions.RemoveCallbacks(IFlightControlsActions)" />
        /// <seealso cref="FlightControlsActions.UnregisterCallbacks(IFlightControlsActions)" />
        public void SetCallbacks(IFlightControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_FlightControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlightControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="FlightControlsActions" /> instance referencing this action map.
    /// </summary>
    public FlightControlsActions @FlightControls => new FlightControlsActions(this);

    // ControlSurfaces
    private readonly InputActionMap m_ControlSurfaces;
    private List<IControlSurfacesActions> m_ControlSurfacesActionsCallbackInterfaces = new List<IControlSurfacesActions>();
    private readonly InputAction m_ControlSurfaces_PitchUp;
    private readonly InputAction m_ControlSurfaces_PitchDown;
    private readonly InputAction m_ControlSurfaces_RollClock;
    private readonly InputAction m_ControlSurfaces_RollCounterClock;
    private readonly InputAction m_ControlSurfaces_YawRight;
    private readonly InputAction m_ControlSurfaces_YawLeft;
    /// <summary>
    /// Provides access to input actions defined in input action map "ControlSurfaces".
    /// </summary>
    public struct ControlSurfacesActions
    {
        private @InputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ControlSurfacesActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ControlSurfaces/PitchUp".
        /// </summary>
        public InputAction @PitchUp => m_Wrapper.m_ControlSurfaces_PitchUp;
        /// <summary>
        /// Provides access to the underlying input action "ControlSurfaces/PitchDown".
        /// </summary>
        public InputAction @PitchDown => m_Wrapper.m_ControlSurfaces_PitchDown;
        /// <summary>
        /// Provides access to the underlying input action "ControlSurfaces/RollClock".
        /// </summary>
        public InputAction @RollClock => m_Wrapper.m_ControlSurfaces_RollClock;
        /// <summary>
        /// Provides access to the underlying input action "ControlSurfaces/RollCounterClock".
        /// </summary>
        public InputAction @RollCounterClock => m_Wrapper.m_ControlSurfaces_RollCounterClock;
        /// <summary>
        /// Provides access to the underlying input action "ControlSurfaces/YawRight".
        /// </summary>
        public InputAction @YawRight => m_Wrapper.m_ControlSurfaces_YawRight;
        /// <summary>
        /// Provides access to the underlying input action "ControlSurfaces/YawLeft".
        /// </summary>
        public InputAction @YawLeft => m_Wrapper.m_ControlSurfaces_YawLeft;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ControlSurfaces; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ControlSurfacesActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ControlSurfacesActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ControlSurfacesActions" />
        public void AddCallbacks(IControlSurfacesActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlSurfacesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlSurfacesActionsCallbackInterfaces.Add(instance);
            @PitchUp.started += instance.OnPitchUp;
            @PitchUp.performed += instance.OnPitchUp;
            @PitchUp.canceled += instance.OnPitchUp;
            @PitchDown.started += instance.OnPitchDown;
            @PitchDown.performed += instance.OnPitchDown;
            @PitchDown.canceled += instance.OnPitchDown;
            @RollClock.started += instance.OnRollClock;
            @RollClock.performed += instance.OnRollClock;
            @RollClock.canceled += instance.OnRollClock;
            @RollCounterClock.started += instance.OnRollCounterClock;
            @RollCounterClock.performed += instance.OnRollCounterClock;
            @RollCounterClock.canceled += instance.OnRollCounterClock;
            @YawRight.started += instance.OnYawRight;
            @YawRight.performed += instance.OnYawRight;
            @YawRight.canceled += instance.OnYawRight;
            @YawLeft.started += instance.OnYawLeft;
            @YawLeft.performed += instance.OnYawLeft;
            @YawLeft.canceled += instance.OnYawLeft;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ControlSurfacesActions" />
        private void UnregisterCallbacks(IControlSurfacesActions instance)
        {
            @PitchUp.started -= instance.OnPitchUp;
            @PitchUp.performed -= instance.OnPitchUp;
            @PitchUp.canceled -= instance.OnPitchUp;
            @PitchDown.started -= instance.OnPitchDown;
            @PitchDown.performed -= instance.OnPitchDown;
            @PitchDown.canceled -= instance.OnPitchDown;
            @RollClock.started -= instance.OnRollClock;
            @RollClock.performed -= instance.OnRollClock;
            @RollClock.canceled -= instance.OnRollClock;
            @RollCounterClock.started -= instance.OnRollCounterClock;
            @RollCounterClock.performed -= instance.OnRollCounterClock;
            @RollCounterClock.canceled -= instance.OnRollCounterClock;
            @YawRight.started -= instance.OnYawRight;
            @YawRight.performed -= instance.OnYawRight;
            @YawRight.canceled -= instance.OnYawRight;
            @YawLeft.started -= instance.OnYawLeft;
            @YawLeft.performed -= instance.OnYawLeft;
            @YawLeft.canceled -= instance.OnYawLeft;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ControlSurfacesActions.UnregisterCallbacks(IControlSurfacesActions)" />.
        /// </summary>
        /// <seealso cref="ControlSurfacesActions.UnregisterCallbacks(IControlSurfacesActions)" />
        public void RemoveCallbacks(IControlSurfacesActions instance)
        {
            if (m_Wrapper.m_ControlSurfacesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ControlSurfacesActions.AddCallbacks(IControlSurfacesActions)" />
        /// <seealso cref="ControlSurfacesActions.RemoveCallbacks(IControlSurfacesActions)" />
        /// <seealso cref="ControlSurfacesActions.UnregisterCallbacks(IControlSurfacesActions)" />
        public void SetCallbacks(IControlSurfacesActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlSurfacesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlSurfacesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ControlSurfacesActions" /> instance referencing this action map.
    /// </summary>
    public ControlSurfacesActions @ControlSurfaces => new ControlSurfacesActions(this);

    // Dev
    private readonly InputActionMap m_Dev;
    private List<IDevActions> m_DevActionsCallbackInterfaces = new List<IDevActions>();
    private readonly InputAction m_Dev_ResetDrone;
    /// <summary>
    /// Provides access to input actions defined in input action map "Dev".
    /// </summary>
    public struct DevActions
    {
        private @InputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public DevActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Dev/ResetDrone".
        /// </summary>
        public InputAction @ResetDrone => m_Wrapper.m_Dev_ResetDrone;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Dev; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="DevActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(DevActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="DevActions" />
        public void AddCallbacks(IDevActions instance)
        {
            if (instance == null || m_Wrapper.m_DevActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DevActionsCallbackInterfaces.Add(instance);
            @ResetDrone.started += instance.OnResetDrone;
            @ResetDrone.performed += instance.OnResetDrone;
            @ResetDrone.canceled += instance.OnResetDrone;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="DevActions" />
        private void UnregisterCallbacks(IDevActions instance)
        {
            @ResetDrone.started -= instance.OnResetDrone;
            @ResetDrone.performed -= instance.OnResetDrone;
            @ResetDrone.canceled -= instance.OnResetDrone;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DevActions.UnregisterCallbacks(IDevActions)" />.
        /// </summary>
        /// <seealso cref="DevActions.UnregisterCallbacks(IDevActions)" />
        public void RemoveCallbacks(IDevActions instance)
        {
            if (m_Wrapper.m_DevActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="DevActions.AddCallbacks(IDevActions)" />
        /// <seealso cref="DevActions.RemoveCallbacks(IDevActions)" />
        /// <seealso cref="DevActions.UnregisterCallbacks(IDevActions)" />
        public void SetCallbacks(IDevActions instance)
        {
            foreach (var item in m_Wrapper.m_DevActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DevActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="DevActions" /> instance referencing this action map.
    /// </summary>
    public DevActions @Dev => new DevActions(this);
    private int m_PCKeyMouseStandardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme PCKeyMouseStandardScheme
    {
        get
        {
            if (m_PCKeyMouseStandardSchemeIndex == -1) m_PCKeyMouseStandardSchemeIndex = asset.FindControlSchemeIndex("PC - KeyMouse (Standard)");
            return asset.controlSchemes[m_PCKeyMouseStandardSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "FlightControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="FlightControlsActions.AddCallbacks(IFlightControlsActions)" />
    /// <seealso cref="FlightControlsActions.RemoveCallbacks(IFlightControlsActions)" />
    public interface IFlightControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Thrust" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrust(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ImpulseThrust" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnImpulseThrust(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AirBrakes" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAirBrakes(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Hovering" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHovering(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MouseScroll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseScroll(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MouseClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseClick(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ControlSurfaces" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ControlSurfacesActions.AddCallbacks(IControlSurfacesActions)" />
    /// <seealso cref="ControlSurfacesActions.RemoveCallbacks(IControlSurfacesActions)" />
    public interface IControlSurfacesActions
    {
        /// <summary>
        /// Method invoked when associated input action "PitchUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPitchUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PitchDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPitchDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RollClock" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRollClock(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RollCounterClock" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRollCounterClock(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "YawRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnYawRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "YawLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnYawLeft(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Dev" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="DevActions.AddCallbacks(IDevActions)" />
    /// <seealso cref="DevActions.RemoveCallbacks(IDevActions)" />
    public interface IDevActions
    {
        /// <summary>
        /// Method invoked when associated input action "ResetDrone" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnResetDrone(InputAction.CallbackContext context);
    }
}
