//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/[Dev4]FlightSim/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""FlightControls"",
            ""id"": ""1b45f00a-3ed4-4d76-865a-c6eda1f0a5a2"",
            ""actions"": [
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Button"",
                    ""id"": ""15f3a9c0-f2f7-4ca6-8905-c70bea263c71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ImpulseThrust"",
                    ""type"": ""Button"",
                    ""id"": ""b07dc9a3-a571-4354-8200-1a8a3abf468b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AirBrakes"",
                    ""type"": ""Button"",
                    ""id"": ""5e48aa2d-fa26-49d9-8312-62403302a761"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hovering"",
                    ""type"": ""Button"",
                    ""id"": ""794bab40-801c-4917-b5dc-5b7340943e0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseScroll"",
                    ""type"": ""Button"",
                    ""id"": ""5e49db7a-66e9-4446-bd98-c059880cc06f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""54bbe36d-2fb5-4cb7-b08e-401b31a88706"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Thrust Controls"",
                    ""id"": ""a7c92610-83ac-4fca-9ace-6f3b1b9b00e8"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""882074c5-3e45-4d26-bb94-5e5c9aa8f5e1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""46b54ed7-a7a9-44c3-bfd9-d2ce934c671b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e654c6af-9686-466a-ad44-c16f567844fb"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""AirBrakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f26ef8fb-fc20-4162-a934-a2d230992622"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""ImpulseThrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f35f32d-76f3-4173-bb70-2ab88f534656"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""Hovering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a342e0b4-d4d5-49ea-aeb2-9b4e1b97def3"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ScrollAxis"",
                    ""id"": ""88616ab2-a41e-489b-a040-5247fa2da8b1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""39340c75-7a98-49d6-b7ad-0eddd72352ca"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0fc4570d-58c1-4316-9393-7f885f2b5518"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""ControlSurfaces"",
            ""id"": ""cf501cd6-3384-431b-ac67-68a563aa565e"",
            ""actions"": [
                {
                    ""name"": ""PitchUp"",
                    ""type"": ""Button"",
                    ""id"": ""9d9ddf46-e7e0-487c-90f9-59a8a915a2c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PitchDown"",
                    ""type"": ""Button"",
                    ""id"": ""0e742c79-d6ca-424f-b0de-ec8a55837695"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollClock"",
                    ""type"": ""Button"",
                    ""id"": ""0a806f74-d753-4dd1-b478-4e2298d72955"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollCounterClock"",
                    ""type"": ""Button"",
                    ""id"": ""9506b580-e4e3-44aa-bff1-291b29297354"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YawRight"",
                    ""type"": ""Button"",
                    ""id"": ""e28b97d5-8f97-43f6-bd2a-856a19de330e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YawLeft"",
                    ""type"": ""Button"",
                    ""id"": ""de49f581-4d65-40e8-9089-4f36be6c3ea6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3688190a-ebe9-4da5-9f92-5d6fdb4e8823"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""PitchUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c835dad-b094-4244-b9d1-bca5d2b7e8cc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""PitchDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56420366-f013-4678-8400-2e8b192c0f5f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""RollClock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c448fb7a-8169-4bbc-9321-21db88e9636f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""RollCounterClock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0544b26b-b39b-479b-86d7-f2ec9f5fe23b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""YawRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59321424-5785-42b0-8a50-e8b42652db78"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC - KeyMouse (Standard)"",
                    ""action"": ""YawLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC - KeyMouse (Standard)"",
            ""bindingGroup"": ""PC - KeyMouse (Standard)"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // FlightControls
        m_FlightControls = asset.FindActionMap("FlightControls", throwIfNotFound: true);
        m_FlightControls_Thrust = m_FlightControls.FindAction("Thrust", throwIfNotFound: true);
        m_FlightControls_ImpulseThrust = m_FlightControls.FindAction("ImpulseThrust", throwIfNotFound: true);
        m_FlightControls_AirBrakes = m_FlightControls.FindAction("AirBrakes", throwIfNotFound: true);
        m_FlightControls_Hovering = m_FlightControls.FindAction("Hovering", throwIfNotFound: true);
        m_FlightControls_MouseScroll = m_FlightControls.FindAction("MouseScroll", throwIfNotFound: true);
        m_FlightControls_MouseClick = m_FlightControls.FindAction("MouseClick", throwIfNotFound: true);
        // ControlSurfaces
        m_ControlSurfaces = asset.FindActionMap("ControlSurfaces", throwIfNotFound: true);
        m_ControlSurfaces_PitchUp = m_ControlSurfaces.FindAction("PitchUp", throwIfNotFound: true);
        m_ControlSurfaces_PitchDown = m_ControlSurfaces.FindAction("PitchDown", throwIfNotFound: true);
        m_ControlSurfaces_RollClock = m_ControlSurfaces.FindAction("RollClock", throwIfNotFound: true);
        m_ControlSurfaces_RollCounterClock = m_ControlSurfaces.FindAction("RollCounterClock", throwIfNotFound: true);
        m_ControlSurfaces_YawRight = m_ControlSurfaces.FindAction("YawRight", throwIfNotFound: true);
        m_ControlSurfaces_YawLeft = m_ControlSurfaces.FindAction("YawLeft", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FlightControls
    private readonly InputActionMap m_FlightControls;
    private IFlightControlsActions m_FlightControlsActionsCallbackInterface;
    private readonly InputAction m_FlightControls_Thrust;
    private readonly InputAction m_FlightControls_ImpulseThrust;
    private readonly InputAction m_FlightControls_AirBrakes;
    private readonly InputAction m_FlightControls_Hovering;
    private readonly InputAction m_FlightControls_MouseScroll;
    private readonly InputAction m_FlightControls_MouseClick;
    public struct FlightControlsActions
    {
        private @InputMap m_Wrapper;
        public FlightControlsActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Thrust => m_Wrapper.m_FlightControls_Thrust;
        public InputAction @ImpulseThrust => m_Wrapper.m_FlightControls_ImpulseThrust;
        public InputAction @AirBrakes => m_Wrapper.m_FlightControls_AirBrakes;
        public InputAction @Hovering => m_Wrapper.m_FlightControls_Hovering;
        public InputAction @MouseScroll => m_Wrapper.m_FlightControls_MouseScroll;
        public InputAction @MouseClick => m_Wrapper.m_FlightControls_MouseClick;
        public InputActionMap Get() { return m_Wrapper.m_FlightControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlightControlsActions set) { return set.Get(); }
        public void SetCallbacks(IFlightControlsActions instance)
        {
            if (m_Wrapper.m_FlightControlsActionsCallbackInterface != null)
            {
                @Thrust.started -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnThrust;
                @Thrust.performed -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnThrust;
                @Thrust.canceled -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnThrust;
                @ImpulseThrust.started -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnImpulseThrust;
                @ImpulseThrust.performed -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnImpulseThrust;
                @ImpulseThrust.canceled -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnImpulseThrust;
                @AirBrakes.started -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnAirBrakes;
                @AirBrakes.performed -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnAirBrakes;
                @AirBrakes.canceled -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnAirBrakes;
                @Hovering.started -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnHovering;
                @Hovering.performed -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnHovering;
                @Hovering.canceled -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnHovering;
                @MouseScroll.started -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnMouseScroll;
                @MouseScroll.performed -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnMouseScroll;
                @MouseScroll.canceled -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnMouseScroll;
                @MouseClick.started -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnMouseClick;
                @MouseClick.performed -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnMouseClick;
                @MouseClick.canceled -= m_Wrapper.m_FlightControlsActionsCallbackInterface.OnMouseClick;
            }
            m_Wrapper.m_FlightControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Thrust.started += instance.OnThrust;
                @Thrust.performed += instance.OnThrust;
                @Thrust.canceled += instance.OnThrust;
                @ImpulseThrust.started += instance.OnImpulseThrust;
                @ImpulseThrust.performed += instance.OnImpulseThrust;
                @ImpulseThrust.canceled += instance.OnImpulseThrust;
                @AirBrakes.started += instance.OnAirBrakes;
                @AirBrakes.performed += instance.OnAirBrakes;
                @AirBrakes.canceled += instance.OnAirBrakes;
                @Hovering.started += instance.OnHovering;
                @Hovering.performed += instance.OnHovering;
                @Hovering.canceled += instance.OnHovering;
                @MouseScroll.started += instance.OnMouseScroll;
                @MouseScroll.performed += instance.OnMouseScroll;
                @MouseScroll.canceled += instance.OnMouseScroll;
                @MouseClick.started += instance.OnMouseClick;
                @MouseClick.performed += instance.OnMouseClick;
                @MouseClick.canceled += instance.OnMouseClick;
            }
        }
    }
    public FlightControlsActions @FlightControls => new FlightControlsActions(this);

    // ControlSurfaces
    private readonly InputActionMap m_ControlSurfaces;
    private IControlSurfacesActions m_ControlSurfacesActionsCallbackInterface;
    private readonly InputAction m_ControlSurfaces_PitchUp;
    private readonly InputAction m_ControlSurfaces_PitchDown;
    private readonly InputAction m_ControlSurfaces_RollClock;
    private readonly InputAction m_ControlSurfaces_RollCounterClock;
    private readonly InputAction m_ControlSurfaces_YawRight;
    private readonly InputAction m_ControlSurfaces_YawLeft;
    public struct ControlSurfacesActions
    {
        private @InputMap m_Wrapper;
        public ControlSurfacesActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @PitchUp => m_Wrapper.m_ControlSurfaces_PitchUp;
        public InputAction @PitchDown => m_Wrapper.m_ControlSurfaces_PitchDown;
        public InputAction @RollClock => m_Wrapper.m_ControlSurfaces_RollClock;
        public InputAction @RollCounterClock => m_Wrapper.m_ControlSurfaces_RollCounterClock;
        public InputAction @YawRight => m_Wrapper.m_ControlSurfaces_YawRight;
        public InputAction @YawLeft => m_Wrapper.m_ControlSurfaces_YawLeft;
        public InputActionMap Get() { return m_Wrapper.m_ControlSurfaces; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlSurfacesActions set) { return set.Get(); }
        public void SetCallbacks(IControlSurfacesActions instance)
        {
            if (m_Wrapper.m_ControlSurfacesActionsCallbackInterface != null)
            {
                @PitchUp.started -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnPitchUp;
                @PitchUp.performed -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnPitchUp;
                @PitchUp.canceled -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnPitchUp;
                @PitchDown.started -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnPitchDown;
                @PitchDown.performed -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnPitchDown;
                @PitchDown.canceled -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnPitchDown;
                @RollClock.started -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnRollClock;
                @RollClock.performed -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnRollClock;
                @RollClock.canceled -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnRollClock;
                @RollCounterClock.started -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnRollCounterClock;
                @RollCounterClock.performed -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnRollCounterClock;
                @RollCounterClock.canceled -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnRollCounterClock;
                @YawRight.started -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnYawRight;
                @YawRight.performed -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnYawRight;
                @YawRight.canceled -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnYawRight;
                @YawLeft.started -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnYawLeft;
                @YawLeft.performed -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnYawLeft;
                @YawLeft.canceled -= m_Wrapper.m_ControlSurfacesActionsCallbackInterface.OnYawLeft;
            }
            m_Wrapper.m_ControlSurfacesActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PitchUp.started += instance.OnPitchUp;
                @PitchUp.performed += instance.OnPitchUp;
                @PitchUp.canceled += instance.OnPitchUp;
                @PitchDown.started += instance.OnPitchDown;
                @PitchDown.performed += instance.OnPitchDown;
                @PitchDown.canceled += instance.OnPitchDown;
                @RollClock.started += instance.OnRollClock;
                @RollClock.performed += instance.OnRollClock;
                @RollClock.canceled += instance.OnRollClock;
                @RollCounterClock.started += instance.OnRollCounterClock;
                @RollCounterClock.performed += instance.OnRollCounterClock;
                @RollCounterClock.canceled += instance.OnRollCounterClock;
                @YawRight.started += instance.OnYawRight;
                @YawRight.performed += instance.OnYawRight;
                @YawRight.canceled += instance.OnYawRight;
                @YawLeft.started += instance.OnYawLeft;
                @YawLeft.performed += instance.OnYawLeft;
                @YawLeft.canceled += instance.OnYawLeft;
            }
        }
    }
    public ControlSurfacesActions @ControlSurfaces => new ControlSurfacesActions(this);
    private int m_PCKeyMouseStandardSchemeIndex = -1;
    public InputControlScheme PCKeyMouseStandardScheme
    {
        get
        {
            if (m_PCKeyMouseStandardSchemeIndex == -1) m_PCKeyMouseStandardSchemeIndex = asset.FindControlSchemeIndex("PC - KeyMouse (Standard)");
            return asset.controlSchemes[m_PCKeyMouseStandardSchemeIndex];
        }
    }
    public interface IFlightControlsActions
    {
        void OnThrust(InputAction.CallbackContext context);
        void OnImpulseThrust(InputAction.CallbackContext context);
        void OnAirBrakes(InputAction.CallbackContext context);
        void OnHovering(InputAction.CallbackContext context);
        void OnMouseScroll(InputAction.CallbackContext context);
        void OnMouseClick(InputAction.CallbackContext context);
    }
    public interface IControlSurfacesActions
    {
        void OnPitchUp(InputAction.CallbackContext context);
        void OnPitchDown(InputAction.CallbackContext context);
        void OnRollClock(InputAction.CallbackContext context);
        void OnRollCounterClock(InputAction.CallbackContext context);
        void OnYawRight(InputAction.CallbackContext context);
        void OnYawLeft(InputAction.CallbackContext context);
    }
}
